// This file is auto-generated by the importFromSketch.py script.
// Any changes made here will be blown away next time the Sketch file is imported.

extension Style {

    public enum MyAsset: String, UIImageConvertable {
        case duration_background = "duration_background"
        case record_button_outer = "record_button_outer"
    }
}