language: objective-c
osx_image: xcode7.3
xcode_project: CameraEngine.xcodeproj

before_install:
  - sudo gem install xcpretty

script:
  - xcodebuild -project CameraEngine.xcodeproj -scheme 'CameraEngine' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c && exit ${PIPESTATUS[0]}
